update kubernetes deploy files
caicloud/harbor pull request #13
Opened 2016-10-27 10:14 UTC by kdada

2016-10-28 01:52 UTC, ScorpioCPH commented
@ddysher please review this, thanks.

2016-10-31 15:04 UTC, deyuanix requested changes

2016-10-31 15:04 UTC, ddysher commented on Deploy/kubernetes/README.md
> +sh ./dockerfiles/build.sh
sh ?  why not bash ?

2016-10-31 15:04 UTC, ddysher commented on Deploy/kubernetes/README.md
> +- harbor/ui:0.4.0
Dont couple verison info in ur README file

2016-10-31 15:04 UTC, ddysher commented on Deploy/kubernetes/README.md
> +#### 2.integrated with k8s
s/integrated with k8s/integration with kubernetes

2016-10-31 15:04 UTC, ddysher commented on Deploy/kubernetes/README.md
> +#create pv & pvc
Add a space between `#` and first word

2016-10-31 15:04 UTC, ddysher commented on Deploy/kubernetes/README.md
> +#### 1.build images
The README is too simple to be useful.

2016-10-31 15:04 UTC, ddysher commented on Deploy/kubernetes/dockerfiles/jobservice.dockerfile
> +FROM golang:1.6.2
Won't habor provide Dockerfile for you ?

2016-10-31 15:04 UTC, ddysher commented on Deploy/kubernetes/dockerfiles/ui.dockerfile
> +FROM golang:1.6.2
A general note: you should separate building and packaging to two different dockerfiles; so you dont end up with large images.

2016-10-31 15:04 UTC, ddysher commented on Deploy/kubernetes/jobservice/jobservice.rc.yaml
> +        image: test.caicloud.io/harbor/jobservice:0.4.0
test.caicloud.io ?  will it work?

Also, make sure to parameterize version

2016-10-31 15:04 UTC, ddysher commented on Deploy/kubernetes/mysql/mysql.rc.yaml
> +    name: mysql-rc
why change label and selector names?

2016-10-31 15:04 UTC, ddysher commented on Deploy/kubernetes/mysql/mysql.svc.yaml
> +  namespace: harbor
dont hardcode namespace

2016-10-31 15:04 UTC, ddysher commented on Deploy/kubernetes/registry/registry.cm.yaml
> +  cert: |
Better to use kubernetes Secret here

2016-10-31 15:06 UTC, ddysher commented
Few comments; haven't gone through details yet.

@ScorpioCPH @kdada upstream code structure has changed; maybe we should rebase to newest version first?

2016-11-02 01:25 UTC, ScorpioCPH commented
Harbor 0.4.5 is released on Oct 31 with `Refactory for new build process`, but I think we should wait a minutes because this version has plenty changes.

2016-11-02 01:33 UTC, kdada commented on Deploy/kubernetes/dockerfiles/jobservice.dockerfile
> +FROM golang:1.6.2
These Dockerfiles are from official repo and different with ours

2016-11-02 01:41 UTC, kdada commented on Deploy/kubernetes/jobservice/jobservice.rc.yaml
> +        image: test.caicloud.io/harbor/jobservice:0.4.0
it won't work,need i push these images to offcial registry of docker or a common registry?

2016-11-03 05:59 UTC, kdada commented on Deploy/kubernetes/mysql/mysql.rc.yaml
> +    name: mysql-rc
for the clear intention

2016-11-03 06:03 UTC, kdada commented on Deploy/kubernetes/mysql/mysql.svc.yaml
> +  namespace: harbor
I removed it

2016-11-11 08:48 UTC, kdada commented
PTAL

@ddysher

2016-11-14 15:32 UTC, deyuanix requested changes
I think most of the files are fine, top comments:
- README must be rewritten
- You don't seem to respect versions as image is hard coded
- If storage is just hostpath, then I don't think PV/PVC is necessary

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/README.md
> +Firstly you need to get docker images of harbor.You can get it by the two ways:
s/First/Firstly

Note, you need to add a space between  '.' and latter; for example, `of harbor. You can`

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/README.md
> +Use **dockerfiles/build.sh** to build images:
The whole section below is about build images; the hierarchy is wrong.

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/pv/log.pv.yaml
> +    storage: 5Gi
How do you know 5Gi is enough? This is a magic number which we don't really want to use in production.

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/pv/log.pv.yaml
> +    storage: 5Gi
Actually, if you are just using hostpath for ur persistent data, there is really no need to use PV and PVC.  You just declare Pod using hostpath, e.g.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
    - name: hostpath
      image: index.caicloud.io/caicloud/hostpath
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: "/etc"
          name: etc
  volumes:
    - name: etc-caicloud
      hostPath:
        path: "/etc"
```

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/README.md
> +# Integration with Kubernetes
The README is not readable, I'll talk with u in person.

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/templates/jobservice.cm.yaml
> +  MYSQL_PWD: "##db_password##"
nit:  I believe it's more common to use `{{` or `{%` as placeholder instead of `##`.  `##` is error prone: it may be treated as comment.

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/templates/nginx.cm.yaml
> +    worker_connections 1024;
Add proper indentation

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/templates/nginx.cm.yaml
> +    worker_connections 1024;
Same for following sections.

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/templates/nginx.cm.yaml
> +    ##4 https_pkey##
Why `##4 https_pkey##` ?  Should it be `##https_pkey##` ?

I know this is used elsewhere, but curious why put a `4` here?

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/templates/registry.cm.yaml
> +          timeout: 3000ms
These are best practice values?

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/ui/ui.rc.yaml
> +        image: harbor/ui
Image is hardcoded here?  This doesn't make sense as you've mentioned in the README that we'll use versioned ones, right?

2016-11-14 15:32 UTC, ddysher commented on Deploy/kubernetes/prepare
> +#!/usr/bin/env python3
If this is python script, then name it `prepare.py`.

2016-11-14 15:36 UTC, ddysher commented
@ScorpioCPH You'd better also take a look?

2016-11-16 06:09 UTC, kdada commented
PTAL

@ddysher

2016-11-22 06:07 UTC, ddysher commented
Theses configs LGTM, @ScorpioCPH to review and merge.

2016-11-24 04:23 UTC, ScorpioCPH commented
Merge for stash.

2016-11-24 04:23 UTC, merged